language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
  - extra-android-m2repository
  - extra-android-support
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew build assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
git: # this is needed because I have ssh urls instead of https
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules # replaces ssh with https
    - git submodule update --init --recursive # clones submodules as needed
after_success:
  - bash <(curl -s https://codecov.io/bash)
